"""Repository write orchestration on top of the GitHub client."""

from __future__ import annotations

from typing import Any, Mapping

from ..clients.github_client import GitHubClient
from ..constants import DEFAULT_BRANCH_PREFIX, DEFAULT_WRITE_MODE
from ..models import PublishResult, RepoFileChange
from ..utils.datetime_utils import utc_now


class RepositoryService:
    """Handles branch creation, file uploads and pull request creation."""

    def __init__(self, client: GitHubClient, config: Mapping[str, Any]):
        self.client = client
        self.config = config

    async def publish_article(
        self,
        *,
        article_path: str,
        article_title: str,
        slug: str,
        article_content: bytes,
        extra_changes: list[RepoFileChange],
    ) -> PublishResult:
        default_branch = str(self.config.get("default_branch", "main"))
        write_mode = str(self.config.get("write_mode", DEFAULT_WRITE_MODE))
        branch = default_branch
        if write_mode == "pr":
            branch = await self._ensure_work_branch(default_branch, slug)

        all_changes = [
            RepoFileChange(
                path=article_path,
                content=article_content,
                message=f"Publish blog article: {article_title}",
            ),
            *extra_changes,
        ]
        commit_sha = ""
        for change in all_changes:
            sha = await self.client.get_file_sha(change.path, branch)
            response = await self.client.put_file(
                path=change.path,
                content=change.content,
                message=change.message,
                branch=branch,
                sha=sha,
            )
            commit_sha = response["commit"]["sha"]

        pr_url = ""
        if write_mode == "pr":
            pr_url = await self.client.create_pull_request(
                title=f"Publish blog article: {article_title}",
                head=branch,
                base=default_branch,
                body=f"Automated publication generated by AstrBot for `{article_title}`.",
            )

        return PublishResult(
            mode=write_mode,
            branch=branch,
            commit_sha=commit_sha,
            article_path=article_path,
            article_title=article_title,
            slug=slug,
            pr_url=pr_url,
        )

    async def _ensure_work_branch(self, default_branch: str, slug: str) -> str:
        prefix = str(self.config.get("pr_branch_prefix", DEFAULT_BRANCH_PREFIX)).strip("/")
        branch = f"{prefix}/{slug}-{utc_now().strftime('%Y%m%d%H%M%S')}"
        sha = await self.client.get_branch_sha(default_branch)
        await self.client.create_branch(branch, sha)
        return branch
