"""Repository write orchestration on top of the GitHub client."""

from __future__ import annotations

from pathlib import PurePosixPath
from typing import Any, Mapping

import yaml

from ..clients.github_client import GitHubClient
from ..constants import (
    DEFAULT_BRANCH_PREFIX,
    DEFAULT_CONTENT_DIR,
    DEFAULT_WRITE_MODE,
    SUPPORTED_WRITE_MODES,
)
from ..exceptions import PluginConfigError
from ..models import (
    ArticleSummary,
    DeleteResult,
    PublishResult,
    PullRequestInfo,
    PullRequestMergeResult,
    RepoFileChange,
)
from ..utils.datetime_utils import utc_now
from ..utils.slug import slugify


class RepositoryService:
    """Handles branch creation, file uploads and pull request creation."""

    def __init__(self, client: GitHubClient, config: Mapping[str, Any]):
        self.client = client
        self.config = config

    async def publish_article(
        self,
        *,
        article_path: str,
        article_title: str,
        slug: str,
        article_content: bytes,
        extra_changes: list[RepoFileChange],
    ) -> PublishResult:
        return await self._write_article(
            article_path=article_path,
            article_title=article_title,
            slug=slug,
            article_content=article_content,
            extra_changes=extra_changes,
            action_label="Publish",
        )

    async def update_article(
        self,
        *,
        article_path: str,
        article_title: str,
        slug: str,
        article_content: bytes,
        extra_changes: list[RepoFileChange],
    ) -> PublishResult:
        return await self._write_article(
            article_path=article_path,
            article_title=article_title,
            slug=slug,
            article_content=article_content,
            extra_changes=extra_changes,
            action_label="Update",
        )

    async def _write_article(
        self,
        *,
        article_path: str,
        article_title: str,
        slug: str,
        article_content: bytes,
        extra_changes: list[RepoFileChange],
        action_label: str,
    ) -> PublishResult:
        article_path = self._ensure_article_path_allowed(article_path)
        default_branch = self._default_branch()
        write_mode = self._write_mode()
        branch = default_branch
        if write_mode == "pr":
            branch = await self._ensure_work_branch(default_branch, slug)

        all_changes = [
            RepoFileChange(
                path=article_path,
                content=article_content,
                message=f"{action_label} blog article: {article_title}",
            ),
            *extra_changes,
        ]
        commit_sha = ""
        for change in all_changes:
            sha = await self.client.get_file_sha(change.path, branch)
            response = await self.client.put_file(
                path=change.path,
                content=change.content,
                message=change.message,
                branch=branch,
                sha=sha,
            )
            commit_sha = response["commit"]["sha"]

        pr_url = ""
        pr_number = 0
        if write_mode == "pr":
            pr_info = await self.client.create_pull_request(
                title=f"{action_label} blog article: {article_title}",
                head=branch,
                base=default_branch,
                body=f"Automated {action_label.lower()} generated by AstrBot for `{article_title}`.",
            )
            pr_url = pr_info.url
            pr_number = pr_info.number

        return PublishResult(
            mode=write_mode,
            branch=branch,
            commit_sha=commit_sha,
            article_path=article_path,
            article_title=article_title,
            slug=slug,
            pr_number=pr_number,
            pr_url=pr_url,
        )

    async def get_pull_request(self, number: int) -> PullRequestInfo:
        return await self.client.get_pull_request(number)

    async def merge_pull_request(
        self,
        *,
        number: int,
        method: str = "squash",
    ) -> PullRequestMergeResult:
        return await self.client.merge_pull_request(number=number, method=method)

    async def list_articles(self, *, limit: int = 10) -> list[ArticleSummary]:
        default_branch = self._default_branch()
        content_dir = self._content_dir()
        items = await self.client.list_directory(content_dir, default_branch)
        files = [
            str(item.get("path", ""))
            for item in items
            if isinstance(item, dict)
            and str(item.get("type", "")) == "file"
            and str(item.get("path", "")).endswith((".md", ".mdx"))
        ]
        files.sort(reverse=True)
        summaries: list[ArticleSummary] = []
        safe_limit = min(max(1, limit), 50)
        for path in files[:safe_limit]:
            try:
                content, _ = await self.client.get_file_content(path, default_branch)
            except Exception:
                content = ""
            title, slug = self._extract_article_metadata(path, content)
            summaries.append(ArticleSummary(title=title, slug=slug, path=path))
        return summaries

    async def delete_article(self, *, target: str) -> DeleteResult:
        default_branch = self._default_branch()
        write_mode = self._write_mode()
        delete_path = await self._resolve_article_path(target=target, branch=default_branch)
        branch = default_branch
        if write_mode == "pr":
            branch = await self._ensure_work_branch(default_branch, self._branch_slug(target))

        sha = await self.client.get_file_sha(delete_path, branch if write_mode == "pr" else default_branch)
        if not sha:
            raise PluginConfigError(f"找不到要删除的文章：{target}")

        response = await self.client.delete_file(
            path=delete_path,
            message=f"Delete blog article: {delete_path}",
            branch=branch,
            sha=sha,
        )
        commit_sha = response["commit"]["sha"]

        pr_number = 0
        pr_url = ""
        if write_mode == "pr":
            pr_info = await self.client.create_pull_request(
                title=f"Delete blog article: {PurePosixPath(delete_path).name}",
                head=branch,
                base=default_branch,
                body=f"Automated deletion generated by AstrBot for `{delete_path}`.",
            )
            pr_number = pr_info.number
            pr_url = pr_info.url

        return DeleteResult(
            mode=write_mode,
            target=target,
            deleted_path=delete_path,
            branch=branch,
            commit_sha=commit_sha,
            pr_number=pr_number,
            pr_url=pr_url,
        )

    async def get_article(self, *, target: str) -> tuple[ArticleSummary, str]:
        default_branch = self._default_branch()
        article_path = await self._resolve_article_path(target=target, branch=default_branch)
        content, _ = await self.client.get_file_content(article_path, default_branch)
        title, slug = self._extract_article_metadata(article_path, content)
        return ArticleSummary(title=title, slug=slug, path=article_path), content

    async def _ensure_work_branch(self, default_branch: str, slug: str) -> str:
        prefix = str(self.config.get("pr_branch_prefix", DEFAULT_BRANCH_PREFIX)).strip("/")
        branch = f"{prefix}/{slug}-{utc_now().strftime('%Y%m%d%H%M%S')}"
        sha = await self.client.get_branch_sha(default_branch)
        await self.client.create_branch(branch, sha)
        return branch

    async def _resolve_article_path(self, *, target: str, branch: str) -> str:
        normalized = target.strip().replace("\\", "/").strip("/")
        if "/" in normalized or normalized.endswith(".md") or normalized.endswith(".mdx"):
            return self._ensure_article_path_allowed(normalized)

        content_dir = self._content_dir()
        items = await self.client.list_directory(content_dir, branch)
        matches: list[str] = []
        slug = normalized.lower()
        for item in items:
            if not isinstance(item, dict):
                continue
            item_type = str(item.get("type", ""))
            item_path = str(item.get("path", ""))
            if item_type != "file":
                continue
            basename = PurePosixPath(item_path).name.lower()
            if basename.endswith(f"-{slug}.md") or basename.endswith(f"-{slug}.mdx") or basename in {
                f"{slug}.md",
                f"{slug}.mdx",
            }:
                matches.append(item_path)

        if not matches:
            raise PluginConfigError(f"在 `{content_dir}` 下找不到 slug 为 `{target}` 的文章。")
        if len(matches) > 1:
            raise PluginConfigError(
                f"找到多篇匹配文章，请改用完整路径删除：{'; '.join(matches)}"
            )
        return matches[0]

    def _default_branch(self) -> str:
        return str(self.config.get("default_branch", "main")).strip() or "main"

    def _write_mode(self) -> str:
        write_mode = str(self.config.get("write_mode", DEFAULT_WRITE_MODE)).strip().lower()
        if write_mode not in SUPPORTED_WRITE_MODES:
            raise PluginConfigError(
                f"write_mode 必须是 {', '.join(sorted(SUPPORTED_WRITE_MODES))} 之一。"
            )
        return write_mode

    def _content_dir(self) -> str:
        content_dir = (
            str(self.config.get("content_dir", DEFAULT_CONTENT_DIR))
            .strip()
            .replace("\\", "/")
            .strip("/")
        )
        if not content_dir or ".." in PurePosixPath(content_dir).parts:
            raise PluginConfigError("content_dir 不能为空，且不能包含上级目录引用。")
        return content_dir

    def _ensure_article_path_allowed(self, path: str) -> str:
        normalized = path.strip().replace("\\", "/").strip("/")
        path_obj = PurePosixPath(normalized)
        if not normalized or ".." in path_obj.parts:
            raise PluginConfigError("文章路径不能为空，且不能包含上级目录引用。")
        if path_obj.suffix.lower() not in {".md", ".mdx"}:
            raise PluginConfigError("文章路径必须以 .md 或 .mdx 结尾。")

        content_root = PurePosixPath(self._content_dir())
        if content_root not in path_obj.parents:
            raise PluginConfigError("文章路径必须位于配置的 content_dir 下。")
        return path_obj.as_posix()

    def _branch_slug(self, target: str) -> str:
        cleaned = target.strip().replace("\\", "/").replace("/", "-")
        cleaned = cleaned.strip("-") or "delete-article"
        return slugify(cleaned, default="delete-article")

    def _extract_article_metadata(self, path: str, content: str) -> tuple[str, str]:
        slug = PurePosixPath(path).stem
        if "-" in slug:
            parts = slug.split("-", 3)
            if len(parts) == 4 and all(parts[i].isdigit() for i in range(3)):
                slug = parts[3]

        title = PurePosixPath(path).stem
        if content.startswith("---"):
            try:
                _, fm, _ = content.split("---", 2)
                metadata = yaml.safe_load(fm) or {}
                if isinstance(metadata, dict):
                    title = str(metadata.get("title", title))
                    slug = str(metadata.get("slug", slug))
            except Exception:
                pass
        return title, slug
